version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - vikoverflow-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: .
    environment:
      - CONFIG_FILE=/code/config.yaml
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  vikoverflow-data:
    external: true
