secret_key: '%kcis5#b-w4axes_v6hmc3&s6ls@xgawhrvqgetp!!(^vba&ms' # WARNING: Dont use in production
authsch:
  secret: secret
  client_id: client_id
debug: True
database:
  user: 'postgres'
  password: ''
  host: 'localhost'
  port: 5432
  name: 'postgres'
allowed_users: ['*']
allowed_hosts: ['*']