# Generated by Django 2.1.7 on 2019-02-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile_deleted"),
        ("account", "0002_auto_20190104_1528"),
    ]

    operations = []
