# Generated by Django 2.2.9 on 2020-02-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190315_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
