# Generated by Django 2.1.3 on 2019-01-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("question", "0001_initial")]

    operations = [
        migrations.AddField(model_name="answer", name="is_visible", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="comment", name="is_visible", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="question", name="is_visible", field=models.BooleanField(default=True)),
    ]
