# Generated by Django 2.1 on 2018-10-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvoters',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvoters',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvoters',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoters',
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvoters',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvoters',
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='common.Votes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='common.Votes'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='common.Votes'),
        ),
    ]
