# Generated by Django 2.1.5 on 2019-01-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20190131_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedquestion',
            name='deleted',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
