# Generated by Django 2.1.5 on 2019-02-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20190122_1919'),
        ('question', '0004_taggedquestion_deleted'),
    ]

    operations = [
    ]
