# Generated by Django 2.1.7 on 2019-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="votes",
            name="downvoters",
            field=models.ManyToManyField(
                null=True, related_name="downvotes", to="account.Profile"
            ),
        ),
        migrations.AlterField(
            model_name="votes",
            name="upvoters",
            field=models.ManyToManyField(
                null=True, related_name="upvotes", to="account.Profile"
            ),
        ),
    ]
