# Generated by Django 2.1.3 on 2018-11-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('question', '0002_auto_20181009_1959'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_username', models.BooleanField()),
                ('text', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_comment_comments', to='account.Profile')),
                ('parent_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.Answer')),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.Question')),
                ('votes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.Votes')),
            ],
        ),
    ]
