# Generated by Django 2.1.3 on 2018-11-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.Answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.Question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='common.Votes'),
        ),
    ]
